### ISSUE TITLE
Corrupted containers on restart using a persistent drive

### ISSUE THREAD

**Issue by kzorba** [Juniper/OpenJNPR-Container-vMX#11]
Using the following docker-compose file

```
version: "2.1"

services:

  vmx1:
    image: juniper/openjnpr-container-vmx:trusty
    hostname: vmx1
    container_name: vmx1
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
    environment:
      - ID=vmx1
      - LICENSE=vMX_license.txt
      - IMAGE=junos-vmx-x86-64-17.3R2.10.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=vmx1.conf
#      - VMXT=vmxt.conf
      - HDDIMAGE=/images/p1.qcow2
    volumes:
      - $PWD/images:/images
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      net0-mgmt:
        ipv4_address: 172.16.0.10
        ipv6_address: fd00::10
      net1-p2p:
        ipv4_address: 10.1.0.5
        ipv6_address: fd00:1::a

  vmx2:
    image: juniper/openjnpr-container-vmx:bionic
    hostname: vmx2
    container_name: vmx2
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
    environment:
      - ID=vmx2
      - LICENSE=vMX_license.txt
      - IMAGE=junos-vmx-x86-64-18.2R1.9.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=vmx2.conf
      - VMXT=vmxt.conf
      - HDDIMAGE=/images/p2.qcow2 # if we want it to be persistant
    volumes:
      - $PWD/images:/images
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      net0-mgmt:
        ipv4_address: 172.16.0.11
        ipv6_address: fd00::11
      net1-p2p:
        ipv4_address: 10.1.0.6
        ipv6_address: fd00:1::b
networks:
  net0-mgmt:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.16.0.0/24
        - subnet: fd00::/64
  net1-p2p:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.1.0.0/24
        - subnet: fd00:1::/64
```

Containers boot fine the first time but if you shut them down with `docker-compose down` on restart they are corrupted (see attached log files).
My environment settings:

```
Linux <hostname> 4.9.0-0.bpo.6-amd64 #1 SMP Debian 4.9.88-1+deb9u1~bpo8+1 (2018-05-13) x86_64 GNU/Linux

$ docker-compose --version
docker-compose version 1.23.1, build b02f1306

$ docker --version
Docker version 18.06.1-ce, build e68fc7a
```
[vmx1_persistent_problem.log.gz](https://github.com/Juniper/OpenJNPR-Container-vMX/files/2717401/vmx1_persistent_problem.log.gz)
[vmx2_persistent_problem.log.gz](https://github.com/Juniper/OpenJNPR-Container-vMX/files/2717402/vmx2_persistent_problem.log.gz)
