### ISSUE TITLE
Support for IPv6 address on fxp0 when IPv6 is enabled in docker networks

### ISSUE THREAD

**Issue by kzorba** [Juniper/OpenJNPR-Container-vMX#9]
When IPv6 addresses are used in docker networks (docker compose 2.x file format) vmx does not properly configure IPv6 on fxp0. A small patch will follow to resolve this.

Example docker-compose.yml:

```
version: "2.1"

services:

  vmx1:
    image: juniper/openjnpr-container-vmx:trusty  
    hostname: vmx1
    container_name: vmx1
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
    environment:
      - ID=vmx1
      - LICENSE=license-eval.txt
      - IMAGE=junos-vmx-x86-64-17.3R2.10.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=vmx1.conf
#      - VMXT=vmxt.conf
#      - HDDIMAGE=/images/p1.qcow2 # if we want it to be persistent
    volumes:
#      - $PWD/images:/images
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      net0-mgmt:
        ipv4_address: 172.16.0.10
        ipv6_address: fd00::10
      net1-p2p:
        ipv4_address: 10.1.0.5
        ipv6_address: fd00:1::a

  vmx2:
    image: juniper/openjnpr-container-vmx:bionic
    hostname: vmx2
    container_name: vmx2
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
    environment:
      - ID=vmx2
      - LICENSE=license-eval.txt
      - IMAGE=junos-vmx-x86-64-18.2R1.9.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=vmx2.conf
      - VMXT=vmxt.conf
#      - HDDIMAGE=/images/p2.qcow2 # if we want it to be persistant
    volumes:
#      - $PWD/images:/images
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      net0-mgmt:
        ipv4_address: 172.16.0.11
        ipv6_address: fd00::11
      net1-p2p:
        ipv4_address: 10.1.0.6
        ipv6_address: fd00:1::b
networks:
  net0-mgmt:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.16.0.0/24
        - subnet: fd00::/64
  net1-p2p:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.1.0.0/24
        - subnet: fd00:1::/64
```
